### ISSUE TITLE
run test_agents.py

### ISSUE THREAD

**Issue by Mintbo** [Brusa99/R-MABM#1]
![1731335475457](https://github.com/user-attachments/assets/b4d06f7a-9c6b-479c-acff-7a2a302a1967)

**Comment by Brusa99** [comment]
This bug was introduced by [version 0.1.3 of ABCredit.jl](https://github.com/bancaditalia/ABCredit.jl/commit/350b64c3f39791c7bd45fe9b1ef63b91990f3fcd).
As a temporary fix I suggest manually installig version 0.1.2 of the Julia package

**Comment by Mintbo** [comment]
Thank you! Could you provide an example of the `__init__.py`  in the `rmabm` folder?

**Comment by Brusa99** [comment]
I'm not sure I understand what you mean.  
The latest update (v0.0.2) of R-MAMB should fix the problem you encountered.

**Comment by Mintbo** [comment]
Yes, thanks for your answer. The previous question has been solved. Now it is a new question. I hope to simulate the R-MABM framework mentioned in the paper and I have downloaded the updated code, but I still don't know how to use the code for simulation. I noticed that the beginning has been written in __init__.py. I am not sure whether it is by writing this file and running it to simulate the experiment in the paper. If yes, could you please tell me how to write this __init__.py or provide an example.
![image](https://github.com/user-attachments/assets/381181ab-eaef-4ea3-9d92-809425769ceb)

**Comment by Brusa99** [comment]
No, that file shouldn't be modified.
I will push some examples later today.
I will also consider putting a brief tutorial in the docs.

**Comment by Mintbo** [comment]
That would be great, I'll be looking forward to the examples and tutorial

**Comment by Brusa99** [comment]
Dear @Mintbo, I put some examples on how to run a basic simulation and RL agent training.
Hope you find it useful.
I'm also planning to add some examples on how to use some python RL libraries with the package.
