### ISSUE TITLE
Upgrade R-MABM to python 3.12

### ISSUE THREAD

**Issue by finmod** [Brusa99/R-MABM#3]
Trying to run the R-MABM examples in Colab for ease and simplicity. The following command signals a need to upgrade R-MABM to 3.12.

!pip install git+https://github.com/Brusa99/R-MABM.git

![image](https://github.com/user-attachments/assets/8042aa8b-d7d6-4f6e-a83a-f29b007a6822)

Would it be possible to upgrade R-MABM instead of downgrading python in Colab?

**Comment by Brusa99** [comment]
Thanks for the feedback.
I changed the requirements for R-MAMB to python >= 3.9, so it should work on collab now.
Please let me know if everything is working correctly.

**Comment by finmod** [comment]
👍Perfect. Please put this mode of testing R-MABM in README

________________________________
